### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [zapier/django-knowledge#70]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like django-knowledge, deleted the software history during the transition to open-source.

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask django-knowledge developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by bryanhelmig** [comment]
`django-knowledge` was just another app in our "monolith", we literally `cp -r`'d it out and into its own repository to open source. The default behavior is that of a "fresh repo" - to try and retain history would have been a ton of work (and can it even be done? no clue).

So, this isn't a case of "let's open source this, nuke the repo and blow away history", it's a case of "externalize this code and open source it". Dropping history was merely a side effect.

**Comment by gustavopinto** [comment]
thank you, @bryanhelmig !

**Comment by gustavopinto** [comment]
Hi @bryanhelmig, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
